name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install depencencies
      run: sudo apt-get install -y libxkbcommon-dev
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: clippy
      uses: auguwu/clippy-action@1.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
